baseURL = "https://juliensoy.netlify.com/"
languageCode = "en-us"
DefaultContentLanguage = "fr"
theme = "hugo-theme-massively"

[languages]
	[languages.en]
	  languageName = "English"
	  title = "Julien Soysouvanh"
	[languages.fr]
	  languageName = "Français"
	  title = "Julien Soysouvanh"
#	[languages.jp]
#	  languageName = "日本語"
#	  title = "ソイスヴァン　ジュリアン"