baseURL = "https://juliensoy.netlify.com/"
languageCode = "en-us"
theme = "hugo-theme-massively"

[languages]
[languages.fr]
  languageName = "Français"
  title = "Julien Soysouvanh"
[languages.en]
  languageName = "English"
  title = "Julien Soysouvanh"
[languages.jp]
  languageName = "日本語"
  title = "ソイスヴァン　ジュリアン"